## Meghna Lohani 16BCE1395

## Lab 9 kmeans on movilens

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv(r'C:\Users\Sathya\Desktop\VIT\VIT 6th sem\MACHINE LEARNING\LAB\movielens\movies.csv')
ratings=pd.read_csv(r'C:\Users\Sathya\Desktop\VIT\VIT 6th sem\MACHINE LEARNING\LAB\movielens\ratings.csv')
tags=pd.read_csv(r'C:\Users\Sathya\Desktop\VIT\VIT 6th sem\MACHINE LEARNING\LAB\movielens\tags.csv')

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
tags.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [22]:
d1=pd.merge(movies,ratings,on='movieId')

In [23]:
d1.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [24]:
mat=d1.pivot(
index='movieId',
columns='userId',
values='rating').fillna(0)

In [25]:
from sklearn.cluster import KMeans
km=KMeans(n_clusters=10)
km.fit(mat)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [27]:
labels=km.labels_
print(labels)

[2 9 8 ... 3 3 3]

In [ ]:
dict={}

In [28]:
def clusterindexnumpy(clustnum,label):
     return np.where(clustnum==label)[0]

In [29]:
a=clusterindexnumpy(3,labels)
print(a)

[   3    8   11 ... 9721 9722 9723]

In [41]:
d3=([movies.loc[movies['movieId']==a1] for a1 in a])

In [43]:
print(d3)

[   movieId                    title          genres
2        3  Grumpier Old Men (1995)  Comedy|Romance,    movieId                title              genres
7        8  Tom and Huck (1995)  Adventure|Children,     movieId                           title                genres
10       11  American President, The (1995)  Comedy|Drama|Romance,     movieId                               title         genres
11       12  Dracula: Dead and Loving It (1995)  Comedy|Horror,     movieId         title                        genres
12       13  Balto (1995)  Adventure|Animation|Children,     movieId                                  title  genres
18       19  Ace Ventura: When Nature Calls (1995)  Comedy,     movieId                title          genres
26       27  Now and Then (1995)  Children|Drama,     movieId                                              title  \
28       29  City of Lost Children, The (Cité des enfants p...

                                    genres
28  Adventure|Drama|Fantasy|Mystery|Sci-Fi  ,     movieId        title          genres
32       34  Babe (1995)  Children|Drama,     movieId                    title       genres
33       36  Dead Man Walking (1995)  Crime|Drama, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],     movieId            title          genres
35       39  Clueless (1995)  Comedy|Romance,     movieId              title                 genres
41       45  To Die For (1995)  Comedy|Drama|Thriller,     movieId              title                                    genres
44       48  Pocahontas (1995)  Animation|Children|Drama|Musical|Romance,     movieId                         title         genres
45       49  When Night Is Falling (1995)  Drama|Romance,     movieId                       title                  genres
46       50  Usual Suspects, The (1995)  Crime|Mystery|Thriller,     movieId                  title           genres
49       54  Big Green, The (1995)  Children|Comedy, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],     movieId                         title genres
51       57  Home for the Holidays (1995)  Drama, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],     movieId                               title                      genres
53       60  Indian in the Cupboard, The (1995)  Adventure|Children|Fantasy,     movieId                                              title        genres
56       63  Don't Be a Menace to South Central While Drink...  Comedy|Crime,     movieId            title  genres
58       65  Bio-Dome (1996)  Comedy,     movieId                                      title                  genres
59       66  Lawnmower Man 2: Beyond Cyberspace (1996)  Action|Sci-Fi|Thriller, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],     movieId          title  genres
61       69  Friday (1995)  Comedy,     movieId             title  genres
63       71  Fair Game (1995)  Action,     movieId                         title        genres
64       72  Kicking and Screaming (1995)  Comedy|Drama,     movieId                title         genres
66       74  Bed of Roses (1996)  Drama|Romance,     movieId             title        genres
67       75  Big Bully (1996)  Comedy|Drama,     movieId             title                  genres
68       76  Screamers (1995)  Action|Sci-Fi|Thriller,     movieId                       title                       genres
70       78  Crossing Guard, The (1995)  Action|Crime|Drama|Thriller,     movieId                            title        genres
74       82  Antonia's Line (Antonia) (1995)  Comedy|Drama,     movieId                      title         genres
76       85  Angels and Insects (1995)  Drama|Romance,     movieId                title                  genres
77       86  White Squall (1996)  Action|Adventure|Drama,     movieId                     title           genres
78       87  Dunston Checks In (1996)  Children|Comedy,     movieId               title  genres
79       88  Black Sheep (1996)  Comedy, Empty DataFrame
Columns: [movieId, title, genres]
Index: [], Empty DataFrame
Columns: [movieId, title, genres]
Index: [],     movieId                       title                 genres
82       93  Vampire in Brooklyn (1995)  Comedy|Horror|Romance,     movieId                   title                genres
83       94  Beautiful Girls (1996)  Comedy|Drama|Romance,     movieId                          title        genres
85       96  In the Bleak Midwinter (1995)  Comedy|Drama,     movieId             title          genres
88      100  City Hall (1996)  Drama|Thriller,     movieId                 title                          genres
89      101  Bottle Rocket (1996)  Adventure|Comedy|Crime|Romance,     movieId             title  genres
90      102  Mr. Wrong (1996)  Comedy,     movieId                 title                   genres
91      103  Unforgettable (1996)  Mystery|Sci-Fi|Thriller,     movieId                                  title         genres
93      105  Bridges of Madison County, The (1995)  Drama|Romance,     movieId                          title                             genres
95      107  Muppet Treasure Island (1996)  Adventure|Children|Comedy|Musical, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],     movieId              title            genres
97      110  Braveheart (1995)  Action|Drama|War,     movieId               title                genres
98      111  Taxi Driver (1976)  Crime|Drama|Thriller,     movieId                                       title  \
99      112  Rumble in the Bronx (Hont faan kui) (1995)

                           genres
99  Action|Adventure|Comedy|Crime  , Empty DataFrame
Columns: [movieId, title, genres]
Index: [], Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                           title  genres
104      119  Steal Big, Steal Little (1995)  Comedy,      movieId                            title genres
105      121  Boys of St. Vincent, The (1992)  Drama,      movieId             title          genres
106      122  Boomerang (1992)  Comedy|Romance,      movieId                          title  genres
108      125  Flirting With Disaster (1996)  Comedy, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                  title          genres
111      129  Pie in the Sky (1996)  Comedy|Romance,      movieId                   title       genres
114      137  Man of the Year (1995)  Documentary,      movieId                 title  genres
116      141  Birdcage, The (1996)  Comedy, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                                title              genres
119      146  Amazing Panda Adventure, The (1995)  Adventure|Children,      movieId           title                genres
122      149  Amateur (1994)  Crime|Drama|Thriller,      movieId             title                genres
123      150  Apollo 13 (1995)  Adventure|Drama|IMAX,      movieId           title                    genres
124      151  Rob Roy (1995)  Action|Drama|Romance|War,      movieId                  title                         genres
126      153  Batman Forever (1995)  Action|Adventure|Comedy|Crime,      movieId                                     title genres
127      154  Beauty of the Day (Belle de jour) (1967)  Drama,      movieId                  title               genres
128      155  Beyond Rangoon (1995)  Adventure|Drama|War,      movieId          title              genres
131      158  Casper (1995)  Adventure|Children,      movieId         title                           genres
133      160  Congo (1995)  Action|Adventure|Mystery|Sci-Fi,      movieId                title              genres
134      161  Crimson Tide (1995)  Drama|Thriller|War,      movieId         title       genres
135      162  Crumb (1994)  Documentary,      movieId                         title                            genres
137      164  Devil in a Blue Dress (1995)  Crime|Film-Noir|Mystery|Thriller,      movieId                              title                 genres
138      165  Die Hard: With a Vengeance (1995)  Action|Crime|Thriller,      movieId                title                genres
140      168  First Knight (1995)  Action|Drama|Romance,      movieId                                    title  \
141      169  Free Willy 2: The Adventure Home (1995)

                       genres
141  Adventure|Children|Drama  ,      movieId           title                           genres
142      170  Hackers (1995)  Action|Adventure|Crime|Thriller,      movieId                   title                  genres
144      172  Johnny Mnemonic (1995)  Action|Sci-Fi|Thriller,      movieId             title  genres
146      174  Jury Duty (1995)  Comedy,      movieId            title         genres
151      179  Mad Love (1995)  Drama|Romance,      movieId            title          genres
152      180  Mallrats (1995)  Comedy|Romance,      movieId                                           title           genres
153      181  Mighty Morphin Power Rangers: The Movie (1995)  Action|Children, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId            title                 genres
156      185  Net, The (1995)  Action|Crime|Thriller,      movieId              title  genres
158      187  Party Girl (1995)  Comedy,      movieId                 title                  genres
159      188  Prophecy, The (1995)  Fantasy|Horror|Mystery,      movieId             title genres
163      193  Showgirls (1995)  Drama,      movieId         title        genres
164      194  Smoke (1995)  Comedy|Drama,      movieId                           title                genres
165      195  Something to Talk About (1995)  Comedy|Drama|Romance,      movieId                title                                      genres
167      198  Strange Days (1995)  Action|Crime|Drama|Mystery|Sci-Fi|Thriller, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                                              title  genres
171      203  To Wong Foo, Thanks for Everything! Julie Newm...  Comedy,      movieId                                 title  genres
172      204  Under Siege 2: Dark Territory (1995)  Action,      movieId                   title        genres
173      205  Unstrung Heroes (1995)  Comedy|Drama,      movieId            title       genres
174      206  Unzipped (1995)  Documentary,      movieId                         title         genres
175      207  Walk in the Clouds, A (1995)  Drama|Romance,      movieId                      title genres
177      209  White Man's Burden (1995)  Drama,      movieId               title                          genres
180      212  Bushwhacked (1995)  Adventure|Comedy|Crime|Mystery,      movieId                                  title     genres
182      214  Before the Rain (Pred dozhdot) (1994)  Drama|War,      movieId                    title        genres
186      218  Boys on the Side (1995)  Comedy|Drama,      movieId             title genres
187      219  Cure, The (1995)  Drama,      movieId                     title         genres
189      222  Circle of Friends (1995)  Drama|Romance,      movieId             title           genres
193      227  Drop Zone (1994)  Action|Thriller,      movieId                              title  genres
194      228  Destiny Turns on the Radio (1995)  Comedy,      movieId                                   title            genres
197      231  Dumb & Dumber (Dumb and Dumber) (1994)  Adventure|Comedy,      movieId                                        title  \
198      232  Eat Drink Man Woman (Yin shi nan nu) (1994)

                   genres
198  Comedy|Drama|Romance  ,      movieId           title genres
199      233  Exotica (1994)  Drama,      movieId                title  genres
200      234  Exit to Eden (1994)  Comedy,      movieId               title                 genres
202      236  French Kiss (1995)  Action|Comedy|Romance,      movieId                title          genres
203      237  Forget Paris (1995)  Comedy|Romance,      movieId            title    genres
206      240  Hideaway (1995)  Thriller,      movieId         title          genres
207      241  Fluke (1995)  Children|Drama,      movieId         title                   genres
209      243  Gordy (1995)  Children|Comedy|Fantasy, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId               title       genres
210      246  Hoop Dreams (1994)  Documentary,      movieId                      title       genres
211      247  Heavenly Creatures (1994)  Crime|Drama,      movieId              title  genres
212      248  Houseguest (1994)  Comedy,      movieId                                title           genres
214      250  Heavyweights (Heavy Weights) (1995)  Children|Comedy,      movieId        title          genres
216      252  I.Q. (1994)  Comedy|Romance,      movieId                   title  genres
219      255  Jerky Boys, The (1995)  Comedy,      movieId          title         genres
220      256  Junior (1994)  Comedy|Sci-Fi,      movieId                                 title  \
222      258  Kid in King Arthur's Court, A (1995)

                                        genres
222  Adventure|Children|Comedy|Fantasy|Romance  ,      movieId                 title                genres
223      259  Kiss of Death (1995)  Crime|Drama|Thriller,      movieId                title genres
225      261  Little Women (1994)  Drama,      movieId                      title          genres
226      262  Little Princess, A (1995)  Children|Drama, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                                              title  \
228      265  Like Water for Chocolate (Como agua para choco...

                    genres
228  Drama|Fantasy|Romance  ,      movieId                       title                     genres
229      266  Legends of the Fall (1994)  Drama|Romance|War|Western,      movieId                                title genres
231      269  My Crazy Life (Mi vida loca) (1993)  Drama,      movieId               title         genres
232      270  Love Affair (1994)  Drama|Romance,      movieId                               title        genres
234      272  Madness of King George, The (1994)  Comedy|Drama,      movieId             title genres
241      279  My Family (1995)  Drama,      movieId                       title          genres
242      280  Murder in the First (1995)  Drama|Thriller,      movieId        title genres
244      282  Nell (1994)  Drama,      movieId                                    title        genres
246      284  New York Cop (Nyû Yôku no koppu) (1993)  Action|Crime, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                        title                 genres
249      288  Natural Born Killers (1994)  Action|Crime|Thriller,      movieId            title          genres
250      289  Only You (1994)  Comedy|Romance,      movieId                      title       genres
251      290  Once Were Warriors (1994)  Crime|Drama,      movieId            title                        genres
253      292  Outbreak (1995)  Action|Drama|Sci-Fi|Thriller,      movieId                                              title  \
254      293  Léon: The Professional (a.k.a. The Professiona...

                          genres
254  Action|Crime|Drama|Thriller  ,      movieId                     title          genres
255      294  Perez Family, The (1995)  Comedy|Romance,      movieId          title genres
259      299  Priest (1994)  Drama,      movieId                              title         genres
261      301  Picture Bride (Bijo photo) (1994)  Drama|Romance,      movieId                                 title  genres
265      305  Ready to Wear (Pret-A-Porter) (1994)  Comedy, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId              title  genres
269      310  Rent-a-Kid (1995)  Comedy,      movieId                           title  genres
271      312  Stuart Saves His Family (1995)  Comedy,      movieId                     title                genres
276      317  Santa Clause, The (1994)  Comedy|Drama|Fantasy,      movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama,      movieId                                              title genres
280      321  Strawberry and Chocolate (Fresa y chocolate) (...  Drama, Empty DataFrame
Columns: [movieId, title, genres]
Index: [],      movieId                  title        genres
282      324  Sum of Us, The (1994)  Comedy|Drama,      movieId             title                genres
285      327  Tank Girl (1995)  Action|Comedy|Sci-Fi,      movieId                          title                  genres
287      329  Star Trek: Generations (1994)  Adventure|Drama|Sci-Fi,      movieId              title            genres
293      335  Underneath (1995)  Mystery|Thriller,      movieId              title                  genres
296      338  Virtuosity (1995)  Action|Sci-Fi|Thriller,      movieId                    title genres
299      341  Double Happiness (1994)  Drama,      movieId                    title  genres
300      342  Muriel's Wedding (1994)  Comedy,      movieId                              title  genres
302      344  Ace Ventura: Pet Detective (1994)  Comedy,      movieId                                              title        genres
303      345  Adventures of Priscilla, Queen of the Desert, ...  Comedy|Drama,      movieId            title         genres
304      346  Backbeat (1993)  Drama|Musical,      movieId               title                   genres
305      347  Bitter Moon (1992)  Drama|Film-Noir|Romance,      movieId                         title  genres
306      348  Bullets Over Broadway (1994)  Comedy,      movieId                            title                       genres
307      349  Clear and Present Danger (1994)  Action|Crime|Drama|Thriller,      movieId               title                  genres
308      350  Client, The (1994)  Drama|Mystery|Thriller,      movieId                    title                genres
309      351  Corrina, Corrina (1994)  Comedy|Drama|Romance,      movieId            title        genres
310      352  Crooklyn (1994)  Comedy|Drama,      movieId             title                         genres
311      353  Crow, The (1994)  Action|Crime|Fantasy|Thriller,      movieId        title genres
312      354  Cobb (1994)  Drama,      movieId                    title                      genres
320      362  Jungle Book, The (1994)  Adventure|Children|Romance,      movieId                                              title       genres
321      363  Wonderful, Horrible Life of Leni Riefenstahl, ...  Documentary,      movieId                                              title  \
324      366  Wes Craven's New Nightmare (Nightmare on Elm S...

                            genres
324  Drama|Horror|Mystery|Thriller  ,      movieId            title                    genres
326      368  Maverick (1994)  Adventure|Comedy|Western,      movieId                                      title genres
327      369  Mrs. Parker and the Vicious Circle (1994)  Drama,      movieId                                      title         genres
328      370  Naked Gun 33 1/3: The Final Insult (1994)  Action|Comedy,      movieId               title           genres
332      374  Richie Rich (1994)  Children|Comedy,      movieId         title                   genres
334      377  Speed (1994)  Action|Romance|Thriller,      movieId                            title         genres
338      381  When a Man Loves a Woman (1994)  Drama|Romance,      movieId          title genres
343      386  S.F.W. (1994)  Drama,      movieId                           title         genres

In [10]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2,random_state=0)
kmeans.fit(movie_features)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [11]:
kmeans.labels_

array([1, 1, 0, ..., 0, 0, 0])

In [12]:
labels=kmeans.predict(movie_features)

In [13]:
print(labels)

[1 1 0 ... 0 0 0]

In [18]:
def ClusterIndicesNumpy(clustNum, labels_array): #numpy 
    return np.where(labels_array == clustNum)[0]

## kmeans clustering

In [13]:
ratings2=pd.merge(ratings,movies,on='movieId')
matrix=pd.pivot_table(ratings2, index='userId',columns='title',values='rating')
print(matrix.head())

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId
1              NaN                                      NaN
2              NaN                                      NaN
3              NaN                                      NaN
4              NaN                                      NaN
5              NaN                                      NaN

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId
1                          NaN                  NaN
2                          NaN                  NaN
3                          NaN                  NaN
4                          NaN                  NaN
5                          NaN                  NaN

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId
1                             NaN                              NaN
2                             NaN                              NaN
3                             NaN                              NaN
4                             NaN                              NaN
5                             NaN                              NaN

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId
1                      NaN                   NaN                          NaN
2                      NaN                   NaN                          NaN
3                      NaN                   NaN                          NaN
4                      NaN                   NaN                          NaN
5                      NaN                   NaN                          NaN

title   *batteries not included (1987)  \
userId
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN

title                     ...                      Zulu (2013)  [REC] (2007)  \
userId                    ...
1                         ...                              NaN           NaN
2                         ...                              NaN           NaN
3                         ...                              NaN           NaN
4                         ...                              NaN           NaN
5                         ...                              NaN           NaN

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId
1                 NaN                      NaN
2                 NaN                      NaN
3                 NaN                      NaN
4                 NaN                      NaN
5                 NaN                      NaN

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
5                                                     NaN

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId
1                   NaN         NaN                             NaN
2                   NaN         NaN                             NaN
3                   NaN         NaN                             NaN
4                   NaN         NaN                             NaN
5                   NaN         NaN                             NaN

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)
userId
1                         4.0                                        NaN
2                         NaN                                        NaN
3                         NaN                                        NaN
4                         NaN                                        NaN
5                         NaN                                        NaN

[5 rows x 9719 columns]

In [22]:
user_movie_ratings=pd.pivot_table(ratings2,index='userId',columns='title',values='rating')
user_movie_ratings.fillna(0)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
582,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
588,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
589,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
591,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
592,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
595,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
598,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
599,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.5,3.0,...,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,2.5,0.0
600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
602,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
603,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0
604,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
605,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.5,3.5,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,...,0.0,4.0,3.5,3.0,0.0,0.0,2.0,1.5,0.0,0.0

In [30]:
#Merging all the dataet

m1=pd.merge(ratings,tags,on=['userId','movieId'],how='left')
m2=pd.merge(m1,movies,on=['movieId'],how='left')
m2.head()

,userId,movieId,rating,timestamp_x,tag,timestamp_y,title,genres
0,1,1,4.0,964982703,NaN,NaN,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,NaN,NaN,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,NaN,NaN,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,NaN,NaN,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,NaN,NaN,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [31]:
m2.describe()

              userId        movieId         rating   timestamp_x   timestamp_y
count  102677.000000  102677.000000  102677.000000  1.026770e+05  3.476000e+03
mean      327.761933   19742.712623       3.514813  1.209495e+09  1.323525e+09
std       183.211289   35884.400990       1.043133  2.170117e+08  1.731554e+08
min         1.000000       1.000000       0.500000  8.281246e+08  1.137179e+09
25%       177.000000    1199.000000       3.000000  1.019138e+09  1.138032e+09
50%       328.000000    3005.000000       3.500000  1.186590e+09  1.279956e+09
75%       477.000000    8366.000000       4.000000  1.439916e+09  1.498457e+09
max       610.000000  193609.000000       5.000000  1.537799e+09  1.537099e+09

In [32]:
m2.isna().sum()

userId             0
movieId            0
rating             0
timestamp_x        0
tag            99201
timestamp_y    99201
title              0
genres             0
dtype: int64

In [34]:
#Counting number of movies in each genre
def count_word(df, ref_col, liste):
    keyword_count = dict()
    for s in liste: keyword_count[s] = 0
    for liste_keywords in df[ref_col].str.split('|'):
        if type(liste_keywords) == float and pd.isnull(liste_keywords): continue
        for s in liste_keywords: 
            if pd.notnull(s): keyword_count[s] += 1
    # convert the dictionary in a list to sort the keywords  by frequency
    keyword_occurences = []
    for k,v in keyword_count.items():
        keyword_occurences.append([k,v])
    keyword_occurences.sort(key = lambda x:x[1], reverse = True)
    return keyword_occurences, keyword_count

In [36]:
#here we  make census of the genres:
genre_labels = set()
for s in m2['genres'].str.split('|').values:
    genre_labels = genre_labels.union(set(s))

In [38]:
#counting how many times each of genres occur:
keyword_occurences, dum = count_word(m2, 'genres', genre_labels)
keyword_occurences

[['Drama', 43024],
 ['Comedy', 39622],
 ['Action', 31151],
 ['Thriller', 27175],
 ['Adventure', 24497],
 ['Romance', 18353],
 ['Sci-Fi', 17691],
 ['Crime', 17224],
 ['Fantasy', 11989],
 ['Children', 9285],
 ['Mystery', 7906],
 ['Horror', 7408],
 ['Animation', 7119],
 ['War', 4931],
 ['IMAX', 4258],
 ['Musical', 4170],
 ['Western', 1966],
 ['Documentary', 1259],
 ['Film-Noir', 880],
 ['(no genres listed)', 49]]

In [39]:
#Convert genres and in rows to columns
#new column is created for every genre

tempDF=m2
for (key,cnt) in keyword_occurences:
    tempDF.loc[tempDF['genres'].str.contains(key), key] = 1
    tempDF[key] = tempDF[key].fillna(0)


tempDF.head()

C:\Users\Sathya\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

,userId,movieId,rating,timestamp_x,tag,timestamp_y,title,genres,Drama,Comedy,...,Mystery,Horror,Animation,War,IMAX,Musical,Western,Documentary,Film-Noir,(no genres listed)
0,1,1,4.0,964982703,NaN,NaN,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3,4.0,964981247,NaN,NaN,Grumpier Old Men (1995),Comedy|Romance,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,6,4.0,964982224,NaN,NaN,Heat (1995),Action|Crime|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,47,5.0,964983815,NaN,NaN,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,50,5.0,964982931,NaN,NaN,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
# Drop Unncecessary Columns

tempDF = tempDF.drop(columns=['title','genres','timestamp_y'])

In [41]:
tempDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102677 entries, 0 to 102676
Data columns (total 25 columns):
userId                102677 non-null int64
movieId               102677 non-null int64
rating                102677 non-null float64
timestamp_x           102677 non-null int64
tag                   3476 non-null object
Drama                 102677 non-null float64
Comedy                102677 non-null float64
Action                102677 non-null float64
Thriller              102677 non-null float64
Adventure             102677 non-null float64
Romance               102677 non-null float64
Sci-Fi                102677 non-null float64
Crime                 102677 non-null float64
Fantasy               102677 non-null float64
Children              102677 non-null float64
Mystery               102677 non-null float64
Horror                102677 non-null float64
Animation             102677 non-null float64
War                   102677 non-null float64
IMAX                  102677 non-null float64
Musical               102677 non-null float64
Western               102677 non-null float64
Documentary           102677 non-null float64
Film-Noir             102677 non-null float64
(no genres listed)    102677 non-null float64
dtypes: float64(21), int64(3), object(1)
memory usage: 20.4+ MB

In [42]:

tempDF['tag'] = tempDF['tag'].fillna('')

In [43]:
# Use tfidf for creating feature vectors tags

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(tempDF['tag'])

In [45]:
ftr = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

In [46]:
tempDF = tempDF.drop(columns=['tag'])

In [47]:
# Concat Features data to actual data

ftrDF = pd.concat([tempDF, ftr], axis=1)
ftrDF.head()

,userId,movieId,rating,timestamp_x,Drama,Comedy,Action,Thriller,Adventure,Romance,...,wrongful,wry,york,younger,zellweger,zither,zoe,zombie,zombies,zooey
0,1,1,4.0,964982703,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3,4.0,964981247,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,6,4.0,964982224,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,47,5.0,964983815,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,50,5.0,964982931,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:

# Run K-means Clustering - with clusters count as 0
# 0 because of number of genres

from sklearn.cluster import KMeans
# Initializing KMeans
kmeans = KMeans(n_clusters=20)
# Fitting with inputs
kmeans = kmeans.fit(ftrDF)
# Predicting the clusters
labels = kmeans.predict(ftrDF)
# Getting the cluster centers
C = kmeans.cluster_centers_

In [50]:

ftrDF.head()

,userId,movieId,rating,timestamp_x,Drama,Comedy,Action,Thriller,Adventure,Romance,...,wrongful,wry,york,younger,zellweger,zither,zoe,zombie,zombies,zooey
0,1,1,4.0,964982703,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3,4.0,964981247,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,6,4.0,964982224,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,47,5.0,964983815,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,50,5.0,964982931,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# To Print the Clusters
import numpy as np
    
clustersvdf=kmeans.fit_predict(ftrDF)
    #print clusters.shape
cluster_0=np.where(clustersvdf==0)
print(cluster_0)

In [52]:
list(np.where(clustersvdf==0))[0]

array([  6882,   6883,   6884, ..., 101334, 101335, 101336], dtype=int64)

In [54]:
m2.iloc[list(np.where(clustersvdf==0))[0]]

,userId,movieId,rating,timestamp_x,tag,timestamp_y,title,genres,Drama,Comedy,...,Mystery,Horror,Animation,War,IMAX,Musical,Western,Documentary,Film-Noir,(no genres listed)
6882,45,50872,5.0,1193288853,NaN,NaN,Ratatouille (2007),Animation|Children|Drama,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6883,45,51080,4.5,1193289356,NaN,NaN,Breach (2007),Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6884,45,53121,4.0,1193288947,NaN,NaN,Shrek the Third (2007),Adventure|Animation|Children|Comedy|Fantasy,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6885,45,53125,4.0,1193288942,NaN,NaN,Pirates of the Caribbean: At World's End (2007),Action|Adventure|Comedy|Fantasy,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6886,45,53322,5.0,1193288932,NaN,NaN,Ocean's Thirteen (2007),Crime|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6887,45,53993,4.5,1193288839,NaN,NaN,Evan Almighty (2007),Comedy|Fantasy,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6888,45,53996,4.5,1193288835,NaN,NaN,Transformers (2007),Action|Sci-Fi|Thriller|IMAX,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6889,45,54272,5.0,1193288817,NaN,NaN,"Simpsons Movie, The (2007)",Animation|Comedy,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6890,45,54286,4.5,1193288697,NaN,NaN,"Bourne Ultimatum, The (2007)",Action|Crime|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10642,66,51255,4.0,1182723476,NaN,NaN,Hot Fuzz (2007),Action|Comedy|Crime|Mystery,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11002,68,2000,3.5,1208743277,NaN,NaN,Lethal Weapon (1987),Action|Comedy|Crime|Drama,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11047,68,2248,3.0,1208744348,NaN,NaN,Say Anything... (1989),Comedy|Drama|Romance,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11258,68,3897,3.5,1198454693,NaN,NaN,Almost Famous (2000),Drama,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11390,68,5618,2.5,1198454699,NaN,NaN,Spirited Away (Sen to Chihiro no kamikakushi) ...,Adventure|Animation|Fantasy,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11406,68,5995,4.0,1208744728,NaN,NaN,"Pianist, The (2002)",Drama|War,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11507,68,8866,4.5,1208743792,NaN,NaN,Wimbledon (2004),Comedy|Romance,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11515,68,8949,3.0,1198454491,NaN,NaN,Sideways (2004),Comedy|Drama|Romance,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11565,68,34405,4.5,1198454346,NaN,NaN,Serenity (2005),Action|Adventure|Sci-Fi,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11575,68,40629,4.0,1198454393,NaN,NaN,Pride & Prejudice (2005),Drama|Romance,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11585,68,41997,3.5,1198454673,NaN,NaN,Munich (2005),Action|Crime|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11593,68,44199,4.0,1208744725,NaN,NaN,Inside Man (2006),Crime|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11615,68,46976,4.0,1208743307,NaN,NaN,Stranger than Fiction (2006),Comedy|Drama|Fantasy|Romance,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11617,68,47610,3.0,1208744739,NaN,NaN,"Illusionist, The (2006)",Drama|Fantasy|Mystery|Romance,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11626,68,48394,4.5,1198454548,NaN,NaN,"Pan's Labyrinth (Laberinto del fauno, El) (2006)",Drama|Fantasy|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11634,68,49530,3.0,1198454751,NaN,NaN,Blood Diamond (2006),Action|Adventure|Crime|Drama|Thriller|War,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11643,68,50872,4.0,1198454471,NaN,NaN,Ratatouille (2007),Animation|Children|Drama,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11644,68,51084,3.5,1208743785,NaN,NaN,Music and Lyrics (2007),Comedy|Romance,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11645,68,51255,4.0,1198454311,NaN,NaN,Hot Fuzz (2007),Action|Comedy|Crime|Mystery,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11647,68,51662,4.0,1198454565,NaN,NaN,300 (2007),Action|Fantasy|War|IMAX,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
11656,68,52722,3.0,1198454680,NaN,NaN,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100834,608,2023,4.5,1189471155,NaN,NaN,"Godfather: Part III, The (1990)",Crime|Drama|Mystery|Thriller,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100929,608,2762,4.5,1189471095,NaN,NaN,"Sixth Sense, The (1999)",Drama|Horror|Mystery,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100973,608,3252,4.0,1189471105,NaN,NaN,Scent of a Woman (1992),Drama,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100987,608,3298,4.5,1189471183,NaN,NaN,Boiler Room (2000),Crime|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101025,608,3717,3.5,1189471151,NaN,NaN,Gone in 60 Seconds (2000),Action|Crime,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101065,608,4034,4.5,1189471092,NaN,NaN,Traffic (2000),Crime|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101144,608,4995,4.5,1189471185,NaN,NaN,"Beautiful Mind, A (2001)",Drama|Romance,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101173,608,5464,4.0,1189471112,NaN,NaN,Road to Perdition (2002),Crime|Drama,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101195,608,5989,4.0,1189471178,NaN,NaN,Catch Me If You Can (2002),Crime|Drama,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101199,608,6059,4.0,1189471116,NaN,NaN,"Recruit, The (2003)",Action|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101205,608,6193,4.5,1189471126,NaN,NaN,Poolhall Junkies (2002),Comedy|Drama|Thriller,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101207,608,6287,4.0,1189471188,NaN,NaN,Anger Management (2003),Comedy,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101223,608,6595,4.0,1189471107,NaN,NaN,S.W.A.T. (2003),Action|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101226,608,6708,4.5,1189471135,NaN,NaN,Matchstick Men (2003),Comedy|Crime|Drama,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101229,608,6754,4.5,1189471086,NaN,NaN,Underworld (2003),Action|Fantasy|Horror,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101239,608,6874,4.0,1189471139,NaN,NaN,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101266,608,7438,4.0,1189471137,NaN,NaN,Kill Bill: Vol. 2 (2004),Action|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101272,608,8132,4.5,1189471168,NaN,NaN,Gladiator (1992),Action|Drama,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101289,608,8784,4.0,1189471174,NaN,NaN,Garden State (2004),Comedy|Drama|Romance,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101314,608,33437,3.5,1189380679,NaN,NaN,Unleashed (Danny the Dog) (2005),Action|Crime|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101320,608,36708,4.0,1189380646,NaN,NaN,Family Guy Presents Stewie Griffin: The Untold...,Adventure|Animation|Comedy,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101328,608,45499,4.0,1189380858,NaN,NaN,X-Men: The Last Stand (2006),Action|Sci-Fi|Thriller,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101329,608,49284,3.5,1189471009,NaN,NaN,10 Items or Less (2006),Comedy|Drama|Romance,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101330,608,51255,4.5,1189563894,NaN,NaN,Hot Fuzz (2007),Action|Comedy|Crime|Mystery,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101331,608,51662,5.0,1189563889,NaN,NaN,300 (2007),Action|Fantasy|War|IMAX,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
101332,608,51903,2.5,1189477736,NaN,NaN,I Think I Love My Wife (2007),Comedy|Drama|Romance,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101333,608,51935,4.0,1189563886,NaN,NaN,Shooter (2007),Action|Drama|Thriller,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101334,608,52245,3.0,1189563917,NaN,NaN,Blades of Glory (2007),Comedy|Romance,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101335,608,53996,5.0,1189380659,NaN,NaN,Transformers (2007),Action|Sci-Fi|Thriller|IMAX,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
101336,608,54503,4.5,1189368725,NaN,NaN,Superbad (2007),Comedy,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
m2.iloc[list(np.where(clustersvdf==0))[0]]['title'].unique()[:50]

array(['Ratatouille (2007)', 'Breach (2007)', 'Shrek the Third (2007)',
       "Pirates of the Caribbean: At World's End (2007)",
       "Ocean's Thirteen (2007)", 'Evan Almighty (2007)',
       'Transformers (2007)', 'Simpsons Movie, The (2007)',
       'Bourne Ultimatum, The (2007)', 'Hot Fuzz (2007)',
       'Lethal Weapon (1987)', 'Say Anything... (1989)',
       'Almost Famous (2000)',
       'Spirited Away (Sen to Chihiro no kamikakushi) (2001)',
       'Pianist, The (2002)', 'Wimbledon (2004)', 'Sideways (2004)',
       'Serenity (2005)', 'Pride & Prejudice (2005)', 'Munich (2005)',
       'Inside Man (2006)', 'Stranger than Fiction (2006)',
       'Illusionist, The (2006)',
       "Pan's Labyrinth (Laberinto del fauno, El) (2006)",
       'Blood Diamond (2006)', 'Music and Lyrics (2007)', '300 (2007)',
       'Spider-Man 3 (2007)', 'Knocked Up (2007)',
       'Live Free or Die Hard (2007)',
       'Harry Potter and the Order of the Phoenix (2007)',
       'Superbad (2007)', '3:10 to Yuma (2007)',
       'American Gangster (2007)', 'No Country for Old Men (2007)',
       'Be Kind Rewind (2008)', 'Cloverfield (2008)',
       'Forgetting Sarah Marshall (2008)',
       'Postman, The (Postino, Il) (1994)', 'Taxi Driver (1976)',
       'Smoke (1995)',
       "Mary Shelley's Frankenstein (Frankenstein) (1994)",
       'Pulp Fiction (1994)',
       'Three Colors: Blue (Trois couleurs: Bleu) (1993)',
       'Three Colors: White (Trzy kolory: Bialy) (1994)',
       "What's Eating Gilbert Grape (1993)", 'Wolf (1994)',
       'In the Name of the Father (1993)', 'Fargo (1996)',
       'Godfather, The (1972)'], dtype=object)

In [56]:
ftrDF = ftrDF.drop(columns='timestamp_x')